from abc import ABC, abstractmethod
from typing import Optional, List
from uuid import UUID
from src.domain.entities import School, Student, Invoice

class SchoolRepository(ABC):
    @abstractmethod
    async def save(self, school: School) -> None: ...
    @abstractmethod
    async def get_by_id(self, school_id: UUID) -> Optional[School]: ...
    @abstractmethod
    async def delete(self, school_id: UUID) -> None: ...
    @abstractmethod
    async def list(self, limit: int, offset: int) -> tuple[List[School], int]: ...

class StudentRepository(ABC):
    @abstractmethod
    async def save(self, student: Student) -> None: ...
    @abstractmethod
    async def get_by_id(self, student_id: UUID) -> Optional[Student]: ...
    @abstractmethod
    async def get_by_school(self, school_id: UUID) -> List[Student]: ...
    @abstractmethod
    async def delete(self, student_id: UUID) -> None: ...
    @abstractmethod
    async def list(self, limit: int, offset: int, school_id: Optional[UUID] = None) -> tuple[List[Student], int]: ...

class InvoiceRepository(ABC):
    @abstractmethod
    async def save(self, invoice: Invoice) -> None: ...
    @abstractmethod
    async def get_by_id(self, invoice_id: UUID) -> Optional[Invoice]: ...
    @abstractmethod
    async def delete(self, invoice_id: UUID) -> None: ...
    @abstractmethod
    async def list(self, limit: int, offset: int, student_id: Optional[UUID] = None) -> tuple[List[Invoice], int]: ...

class UnitOfWork(ABC):
    @abstractmethod
    async def commit(self) -> None: ...
    @abstractmethod
    async def rollback(self) -> None: ...

from src.application.dtos import AccountStatementDTO

class StatementRepository(ABC):
    @abstractmethod
    async def get_student_statement(self, student_id: UUID) -> Optional[AccountStatementDTO]: ...
    
    @abstractmethod
    async def get_school_statement(self, school_id: UUID) -> Optional[AccountStatementDTO]: ...
